import React from "react";
import { Globe, BrainCircuit, FileCode2, BookOpenText, SearchCode } from "lucide-react";

export const coolEndpoints = [
  {
    id: "tools-websearch",
    title: "DuckDuckGo Web Search",
    category: "AI & Smart Tools",
    method: "GET",
    path: "/api/tools/image-search",
    description: "Search the web directly using DuckDuckGo to get top results and links.",
    params: [{ name: "q", type: "string", description: "Search query" }],
    icon: <Globe className="w-5 h-5" />,
    example: "/api/tools/image-search?q=cat+memes",
  },
  {
    id: "nlp-sentiment",
    title: "Sentiment Analysis",
    category: "AI & Smart Tools",
    method: "GET",
    path: "/api/nlp/sentiment",
    description: "Analyze the sentiment (positive/negative/neutral) of an English text.",
    params: [{ name: "text", type: "string", description: "English sentence to analyze" }],
    icon: <BrainCircuit className="w-5 h-5" />,
    example: "/api/nlp/sentiment?text=I+absolutely+love+this+amazing+api",
  },
  {
    id: "nlp-spellcheck",
    title: "Spell Checker",
    category: "AI & Smart Tools",
    method: "GET",
    path: "/api/nlp/spell-check",
    description: "Check if a common English tech word is spelled correctly and get suggestions.",
    params: [{ name: "word", type: "string", description: "Single word to check" }],
    icon: <SearchCode className="w-5 h-5" />,
    example: "/api/nlp/spell-check?word=javascrip",
  },
  {
    id: "tools-html2md",
    title: "HTML to Markdown",
    category: "Tools & Utilities",
    method: "POST",
    path: "/api/tools/html-to-markdown",
    description: "Convert raw HTML code into clean Markdown format.",
    body: [{ name: "html", type: "string", description: "HTML code string" }],
    icon: <FileCode2 className="w-5 h-5" />,
    example: '{"html": "<h1>Hello</h1><p>This is <b>bold</b></p>"}',
  },
  {
    id: "tools-readweb",
    title: "Website Reader (Markdown)",
    category: "Tools & Utilities",
    method: "GET",
    path: "/api/tools/read-web",
    description: "Scrape any website and return its content in readable Markdown format.",
    params: [{ name: "url", type: "string", description: "Target Website URL" }],
    icon: <BookOpenText className="w-5 h-5" />,
    example: "/api/tools/read-web?url=https://en.wikipedia.org/wiki/API",
  }
];
