import React from "react";
import { Globe, Github, BookA, CloudSun, Smile, Quote, Image as ImageIcon } from "lucide-react";

export const usefulEndpoints = [
  {
    id: "info-ip",
    title: "IP Lookup",
    category: "Useful Information",
    method: "GET",
    path: "/api/info/ip",
    description: "Get geographical info for an IP address.",
    params: [{ name: "ip", type: "string", description: "IP Address (optional, uses requester IP if empty)" }],
    icon: <Globe className="w-5 h-5" />,
    example: "/api/info/ip?ip=8.8.8.8",
  },
  {
    id: "info-github-user",
    title: "GitHub User Info",
    category: "Useful Information",
    method: "GET",
    path: "/api/info/github-user",
    description: "Get GitHub profile information.",
    params: [{ name: "username", type: "string", description: "GitHub username" }],
    icon: <Github className="w-5 h-5" />,
    example: "/api/info/github-user?username=torvalds",
  },
  {
    id: "info-github-repo",
    title: "GitHub Repo Info",
    category: "Useful Information",
    method: "GET",
    path: "/api/info/github-repo",
    description: "Get GitHub repository information.",
    params: [{ name: "repo", type: "string", description: "Format: owner/repo" }],
    icon: <Github className="w-5 h-5" />,
    example: "/api/info/github-repo?repo=facebook/react",
  },
  {
    id: "info-dictionary",
    title: "Dictionary Definition",
    category: "Useful Information",
    method: "GET",
    path: "/api/info/dictionary",
    description: "Get English definition and phonetics of a word.",
    params: [{ name: "word", type: "string", description: "English word to look up" }],
    icon: <BookA className="w-5 h-5" />,
    example: "/api/info/dictionary?word=developer",
  },
  {
    id: "info-weather",
    title: "Weather Info",
    category: "Useful Information",
    method: "GET",
    path: "/api/info/weather",
    description: "Get current weather for a city.",
    params: [{ name: "city", type: "string", description: "City name" }],
    icon: <CloudSun className="w-5 h-5" />,
    example: "/api/info/weather?city=Jakarta",
  },
  {
    id: "fun-joke",
    title: "Random Joke",
    category: "Entertainment",
    method: "GET",
    path: "/api/fun/joke",
    description: "Get a random joke.",
    params: [],
    icon: <Smile className="w-5 h-5" />,
    example: "/api/fun/joke",
  },
  {
    id: "fun-quote",
    title: "Random Quote",
    category: "Entertainment",
    method: "GET",
    path: "/api/fun/quote",
    description: "Get a random famous quote.",
    params: [],
    icon: <Quote className="w-5 h-5" />,
    example: "/api/fun/quote",
  },
  {
    id: "tools-screenshot",
    title: "Website Screenshot",
    category: "Media Tools",
    method: "GET",
    path: "/api/tools/screenshot",
    description: "Generate a screenshot URL for a given website.",
    params: [{ name: "url", type: "string", description: "Target URL (e.g. https://google.com)" }],
    icon: <ImageIcon className="w-5 h-5" />,
    example: "/api/tools/screenshot?url=https://github.com",
  },
];
